project:
  name: "Kasparro Agentic Facebook Analyst"
  version: "1.0.0"
  seed: 42
  mode: "sample"

paths:
  data: "data/synthetic_fb_ads_undergarments.csv"
  logs: "logs/"
  reports: "reports/"
  prompts: "prompts/"

thresholds:
  low_ctr: 0.015
  roas_drop_pct: 0.20  # 20% drop threshold for alert

llm:
  provider: "google"
  model: "gemini-2.0-flash"

logging:
  level: "INFO"
  structured: true